### ISSUE TITLE
ALPS+YAML representation

### ISSUE THREAD

**Issue by filip26** [filip26/alps-cli#20]
**Is your feature request related to a problem? Please describe.**
ALPS+YAML should be supported as an alternative representation to ALPS+XML and ALPS+JSON

**Describe the solution you'd like**
To keep the new representation simple and coherent with the existing ones a strict YAML approach should be taken.

**Comment by mamund** [comment]
I've added some YAML examples to the profile repo here: https://github.com/alps-io/profiles/tree/master/yaml

i suggest we start w/ those and see if they expose problems, challenges, and explore fixes/alternatives.

cool?

**Comment by filip26** [comment]
Yes! Thank you for the examples, I'll work with them, so far it seems that the examples conform to strict YAML.

**Comment by mamund** [comment]
:+1:
